export const OPEN_POPUP = 'OPEN_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';
export const ADD_EXAM_POPUP = 'ADD_EXAM_POPUP';
export const ADD_COURSE_POPUP = 'ADD_COURSE_POPUP';
export const EDIT_COURSE_POPUP = 'EDIT_COURSE_POPUP';
export const ADD_SECTION_POPUP = 'ADD_SECTION_POPUP';